import { Nunito } from 'next/font/google'
import './globals.css'

import Navbar from './components/navbar/Navbar';
import ClientOnly from './components/ClientOnly';
import RegisterModal from './components/modals/RegisterModal';
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from './components/modals/LoginModal';
import getCurrentUser from './actions/getCurrentUser';
import RentModal from './components/modals/RentModal';

export const metadata = {
  title: 'AirBnb Clone',
  description: 'Generated by Astha',
}

const font =Nunito({
  subsets: [ "latin"],
});



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className='{font.className}'>
        <ClientOnly>
        <ToasterProvider/>
          <RentModal />
          <RegisterModal/>
          <LoginModal />
          <Navbar currentUser={currentUser} />   {/*hydration err:: server no plain obj iff passed to client without changes of datetime */}
        </ClientOnly>
        {children}</body>
    </html>
  )
}
